import type { TrackProps } from "./components/Track";

export const MOCKED_TRACKLIST: TrackProps[] = [
  { title: "Fortnight (feat. Post Malone)", order: 1, duration: "3:48" },
  { title: "The Tortured Poets Department", order: 2, duration: "4:53" },
  { title: "My Boy Only Breaks His Favorite Toys", order: 3, duration: "3:23" },
  { title: "Down Bad", order: 4, duration: "4:21" },
  { title: "So Long, London", order: 5, duration: "4:22" },
  { title: "But Daddy I Love Him", order: 6, duration: "5:40" },
  { title: "Fresh Out the Slammer", order: 7, duration: "3:30" },
  {
    title: "Florida!!! (feat. Florence + the Machine)",
    order: 8,
    duration: "3:35",
  },
  { title: "Guilty as Sin?", order: 9, duration: "4:14" },
  { title: "Who's Afraid of Little Old Me?", order: 10, duration: "5:34" },
  { title: "I Can Fix Him (No Really I Can)", order: 11, duration: "2:36" },
  { title: "loml", order: 12, duration: "4:37" },
  { title: "I Can Do It With a Broken Heart", order: 13, duration: "3:38" },
  { title: "The Smallest Man Who Ever Lived", order: 14, duration: "4:05" },
  { title: "The Alchemy", order: 15, duration: "3:16" },
  { title: "Clara Bow", order: 16, duration: "3:36" },
  { title: "The Black Dog", order: 17, duration: "3:58" },
  { title: "imgonnagetyouback", order: 18, duration: "3:42" },
  { title: "The Albatross", order: 19, duration: "3:03" },
  { title: "Chloe or Sam or Sophia or Marcus", order: 20, duration: "3:33" },
  { title: "How Did It End?", order: 21, duration: "3:58" },
  { title: "So High School", order: 22, duration: "3:48" },
  { title: "I Hate It Here", order: 23, duration: "4:03" },
  { title: "thanK you aIMee", order: 24, duration: "4:23" },
  { title: "I Look in People's Windows", order: 25, duration: "2:11" },
  { title: "The Prophecy", order: 26, duration: "4:09" },
  { title: "Cassandra", order: 27, duration: "4:00" },
  { title: "Peter", order: 28, duration: "4:43" },
  { title: "The Bolter", order: 29, duration: "3:58" },
  { title: "Robin", order: 30, duration: "4:00" },
  { title: "The Manuscript", order: 31, duration: "3:44" },
];
